s="Tops Technologies"

print(s)
print(s.capitalize())
print(s.casefold())
print(s.center(40,"%"))
print(s.count("o"))
print(s.endswith("gies"))
print(s.find("log"))
print(s.index("T",2))
print("tops123".isalnum())
print("tops".isalnum())
print("2123".isalnum())
print("tops 123".isalnum())
print("tops".isalpha())
print("123".isnumeric())
print(s.istitle())
print(" ".isspace())
print("tops".islower())
print("TOPS".isupper())
print(s.lower())
print(s.upper())
print(s.swapcase())
print(s.replace("o","u"))
for i in s:
    print(i)
